### ISSUE TITLE
Draw shapes example on JSFiddle is outdated

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/camera-enhancer-docs-js#49]
The JSFiddle link for Draw Shapes is outdated. We should update it!

https://www.dynamsoft.com/camera-enhancer/docs/web/programming/javascript/user-guide/features/draw-shapes.html#try-it-out

**Comment by Tom-Dynamsoft** [comment]
@Shen-wb Can you help update this fiddle. Thanks!

**Comment by Tom-Dynamsoft** [comment]
Fixed by updating the link to a different one which does use the new DCE
