### ISSUE TITLE
Incorrect function call in `Add a DrawingLayer` sample code

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/camera-enhancer-docs-js#51]
Location: `L51` on https://github.com/dynamsoft-docs/camera-enhancer-docs-js/blob/main/programming/javascript/user-guide/features/draw-shapes.md?plain=1

createDrawingLater() is under the CameraView class but the example is under `cameraEnhancer`.

**Comment by Tom-Dynamsoft** [comment]
Fixed in pull request #54
